name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          mkdir temp_supabase
          wget https://github.com/supabase/cli/releases/download/v2.23.4/supabase_linux_amd64.tar.gz -O temp_supabase/supabase.tar.gz
          tar -xzf temp_supabase/supabase.tar.gz -C temp_supabase
          chmod +x temp_supabase/supabase
          sudo mv temp_supabase/supabase /usr/local/bin/supabase

      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref qwaooajgkkqtpbidzumd

      - name: Deploy function to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy fetch-loyverse-receipts

      - name: Invoke the function after deployment
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions invoke fetch-loyverse-receipts --project-ref qwaooajgkkqtpbidzumd --no-verify-jwt
