name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          wget https://github.com/supabase/cli/releases/download/v2.23.4/supabase_linux_amd64.tar.gz -O supabase.tar.gz
          tar -xzf supabase.tar.gz supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Deploy function to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy fetch-loyverse-receipts --project-ref qwaooajgkkqtpbidzumd
