name: Deploy Edge Function

on:
  push:
    paths:
      - 'supabase/functions/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Supabase CLI
        run: |
          wget https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 -O supabase-cli
          chmod +x supabase-cli
          sudo mv supabase-cli /usr/local/bin/supabase

      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: qwaooajgkkqtpbidzumd
        run: supabase functions deploy fetch-loyverse-receipts --project-ref $SUPABASE_PROJECT_REF
