# .github/workflows/schedule-generate-triggers.yml

name: Daily Trigger Generator

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 AM UTC = 9:00 AM Bahrain
  workflow_dispatch:

jobs:
  run-generate-triggers:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function: generate-triggers
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/generate-triggers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
