# .github/workflows/run-refresh-triggers.yml
name: Run Refresh Triggers

on:
  workflow_dispatch:  # يسمح بتشغيلها يدويًا من واجهة GitHub
  schedule:
    - cron: '0 3 * * *'  # تشغيل تلقائي يوميًا الساعة 3 صباحًا UTC

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh_triggers SQL function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/refresh_triggers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{}'
