# .github/workflows/run-generate-triggers.yml
name: Run Generate Triggers

on:
  workflow_dispatch:  # يسمح بتشغيلها يدويًا

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call generate-triggers function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/generate-triggers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
