name: Daily Enriched Customers Cache Update

on:
  schedule:
    - cron: '0 3 * * *'  # كل يوم الساعة 6 صباحًا بتوقيت البحرين (3:00 UTC)
  workflow_dispatch:

jobs:
  call-edge-function:
    runs-on: ubuntu-latest

    steps:
      - name: Call update-enriched-customers Edge Function with longer timeout
        run: |
          curl --max-time 300 -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/update-enriched-customers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
