# .github/workflows/schedule-update-enriched-customers.yml

name: Daily Update Enriched Customers

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 9:00 AM Bahrain time (6:00 AM UTC)
  workflow_dispatch:

jobs:
  trigger-update-enriched-customers:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/update-enriched-customers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
