name: Run Refresh Enriched Customers Cache

on:
  workflow_dispatch:  # يسمح بتشغيلها يدويًا
  schedule:
    - cron: '0 2 * * *'  # يوميًا الساعة 2 صباحًا UTC (5 صباحًا بتوقيت البحرين)

jobs:
  refresh-enriched-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh_enriched_customers_cache SQL function and print result
        run: |
          echo "📡 Calling Supabase RPC: refresh_enriched_customers_cache"
          RESPONSE=$(curl -s -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/refresh_enriched_customers_cache" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{}')

          echo "✅ Enriched Cache Refresh Result:"
          echo "$RESPONSE"
