name: Sync New Customers Every 12 Hours

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke sync-customers function
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "Using access token: ${ACCESS_TOKEN:0:5}***"
          curl -X POST "https://qwaooajgkkqtpbidzumd.supabase.co/functions/v1/sync-customers" \
            -H "x-loyverse-token: ${ACCESS_TOKEN}"
