name: Sync Loyverse Receipts Every 10 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # كل 10 دقائق
  workflow_dispatch:

jobs:
  sync-receipts:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke fetch-loyverse-receipts function
        run: |
          echo "Invoking fetch-loyverse-receipts function..."
          curl -X POST "https://qwaooajgkkqtpbidzumd.supabase.co/functions/v1/fetch-loyverse-receipts" \
            -H "x-loyverse-token: ${{ secrets.ACCESS_TOKEN }}"
