name: Sync Loyverse Customers Every 12 Hours

on:
  schedule:
    - cron: "0 */12 * * *"  # كل 12 ساعة
  workflow_dispatch:

jobs:
  sync-customers:
    runs-on: ubuntu-latest
    steps:
      - name: Print token prefix
        run: echo "Calling function with token prefix: ${ACCESS_TOKEN:0:5}***"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Invoke Supabase Edge Function
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl -X POST "https://qwaooajgkkqtpbidzumd.supabase.co/functions/v1/sync-customers" \
            -H "Authorization: Bearer $ACCESS_TOKEN"
