name: Sync Loyverse Customers Every 12 Hours

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  sync-customers:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Edge Function
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "Invoking sync-customers function..."
          curl -X POST "https://qwaooajgkkqtpbidzumd.supabase.co/functions/v1/sync-customers" \
            -H "Authorization: Bearer $ACCESS_TOKEN"
