name: Sync New Customers Every 12 Hours

on:
  schedule:
    - cron: "0 */12 * * *"  # كل 12 ساعة
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke sync-customers function
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl -X POST "https://qwaooajgkkqtpbidzumd.supabase.co/functions/v1/sync-customers" \
            -H "x-loyverse-token: $ACCESS_TOKEN"
